### ISSUE TITLE
Clarify the image upload by mentionning it's a Multipart field

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/api-documentation#32]
Clarify the image upload by mentionning it's a Multipart field
as reported by @ocervell

**Comment by teolemon** [comment]
Should be fixed @ocervell 
https://openfoodfacts.github.io/api-documentation/#jump-4WRITERequests-Addaphototoanexistingproduct

**Comment by ocervell** [comment]
I think the API route in the request example is still wrong, the correct request should be:
```
curl -u off:off -F "code=1234567890123" -F "imagefield=front_fr" -F "imgupload_front_fr=@/Users/ocervello/Downloads/1631031226333.jpg" https://fr.openfoodfacts.net/cgi/product_image_upload.pl
```
